# Generated by Django 5.0.1 on 2024-02-03 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_crud_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table=None,
        ),
    ]
